//! The `antigravity-oauth` provider preset: Google-native models served
//! via Google Antigravity OAuth subscription.

use nuo_model_codec::reasoning::ReasoningSupport;
use nuo_model_codec::{Model, WireProtocol};

use nuo_provider::*;

/// Models served by Google Antigravity OAuth (Google One AI Premium / Pro).
///
/// This is the **offline floor** (Layer 3 of the three-layer catalog): the live
/// catalog at `/v1internal:fetchAvailableModels` is authoritative for a
/// signed-in account and may add generations this seed does not list. The seed
/// stays current enough that a connection with no network still offers the
/// current tiered generation.
pub use nuo_model_codec::model_providers::ANTIGRAVITY_OAUTH_MODELS;

/// Baseline capability metadata for the models this provider serves.
pub const MODELS: &[Model] = &[
    Model {
        id: "gemini-3.8-flash-tiered",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.7-flash-tiered",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.7-flash-high",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.7-flash-medium",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.7-flash-low",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.6-flash-high",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.6-flash-medium",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.6-flash-low",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3-flash-agent",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: &[],
    },
    Model {
        id: "gemini-3-flash",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: &[],
    },
    Model {
        id: "gemini-3.5-flash-low",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_LEVEL,
    },
    Model {
        id: "gemini-3.1-pro-high",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: &[],
    },
    Model {
        id: "gemini-3.1-pro-low",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: &[],
    },
    Model {
        id: "gemini-pro-agent",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: &[],
    },
    Model {
        id: "gemini-2.5-flash",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_BUDGET,
    },
    Model {
        id: "gemini-2.5-flash-thinking",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_BUDGET,
    },
    Model {
        id: "gemini-2.5-pro",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: effort_ladders::GEMINI_BUDGET,
    },
    Model {
        id: "gemini-3.1-flash-lite",
        family: "google",
        context_window: 1_000_000,
        thinking: ReasoningSupport::ReasoningContent,
        tool_call: true,
        vision: true,
        protocol: WireProtocol::GoogleGemini,
        model_guidance: "",
        effort_levels: &[],
    },
];

inventory::submit!(nuo_model_codec::model::BaselineModels(MODELS));

pub const MODEL_PROVIDER_SPEC: ModelProviderSpec = ModelProviderSpec {
    dialect: nuo_model_codec::ProviderDialect::Antigravity,
    protocol_roots: std::borrow::Cow::Borrowed(&[]),
    catalog_root_url: None,
    prompt_cache: nuo_provider::PromptCachePolicy::Compiled(nuo_provider::unsupported_prompt_cache),
    id: std::borrow::Cow::Borrowed("google-antigravity"),
    baselines: MODELS,
    root_url: std::borrow::Cow::Borrowed("https://daily-cloudcode-pa.googleapis.com"),
    user_agent: Some(std::borrow::Cow::Borrowed(
        nuo_model_codec::client_identity::ANTIGRAVITY_USER_AGENT,
    )),
    protocol: WireProtocol::GoogleGemini,
    catalog_source: RemoteCatalogSource::Endpoint(CatalogShape::GoogleCloudCode),
    default_client_profile: nuo_model_codec::ClientPreset::Antigravity,
    client_profile_sensitive: true,
    quota: Some(nuo_provider::QuotaPort::Antigravity),
    models: ANTIGRAVITY_OAUTH_MODELS,
};
