// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningSupport } from "./ReasoningSupport";
import type { WireProtocol } from "./WireProtocol";

/**
 * One user-declared model on a preset or connection scope (ADR-0199): a hidden,
 * preview, or unlisted upstream id pinned to a scope with optional capability facts.
 */
export type DeclaredModel = { 
/**
 * Explicit wire protocol for this model within its provider or connection scope.
 */
protocol: WireProtocol | null, 
/**
 * Exact model id sent on the wire and shown in the picker.
 */
id: string, 
/**
 * Context window in tokens, when the user knows it.
 */
context_window: number | null, 
/**
 * Maximum generated tokens, when known.
 */
max_output_tokens: number | null, 
/**
 * Reasoning representation, when known.
 */
thinking: ReasoningSupport | null, 
/**
 * Image-input support, when known.
 */
vision: boolean | null, 
/**
 * Native tool-call support, when known.
 */
tool_call: boolean | null, };
