// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Availability } from "../../web/src/lib/generated/wire.gen";

/**
 * Provider model info advertised by a connection.
 */
export type ProviderModelInfo = { 
/**
 * Wire model id. Mirrors an entry in [`ProviderPickerRow::models`].
 */
model: string, name?: string | null, protocol: string, effort: string | null, thinking: boolean | null, effort_levels?: Array<string>, favorite: boolean, last_used_ms: bigint | null, vision?: boolean | null, context_window: number, max_output_tokens?: number | null, availability?: Availability | null, availability_overridden?: boolean, advertised?: boolean | null, availability_stale?: boolean, };
