// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The exact inference wire protocol used by a route. Provider dialects alter
 * authentication and envelopes without changing this protocol identity.
 */
export type WireProtocol = "chat-completions" | "responses" | "anthropic-messages" | "google-gemini";
