// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookEventKind = "SessionStart" | "SessionEnd" | "UserPromptSubmit" | "PreToolUse" | "PostToolUse" | "PostToolUseFailure" | "Stop" | "PreCompact" | "PostCompact" | "Turn" | "TurnStart" | "PermissionRequest" | "UserQuestion";
