// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Linux process termination / intercept specification submitted by command execution tools.
 */
export type ProcessKillSpec = { 
/**
 * The base command or binary (e.g. "cargo", "npm", "python", "rm").
 */
command: string, 
/**
 * Whether the spawned process runs in its own process group and can be reaped via killpg / -$PGID.
 */
process_group_killable: boolean, 
/**
 * Standard pkill pattern (e.g. "pkill -P $PID" or "pkill -f <command>").
 */
pkill_target: string, 
/**
 * Working directory where the command will execute.
 */
cwd: string | null, };
