/**
 * Wire contracts for the muta web client.
 *
 * The payload types are GENERATED from `crates/muta-contracts` — the serde
 * source of truth for the session-daemon WebSocket protocol per
 * `docs/reference/server-api.md` § "Contract maintenance" — by ts-rs into
 * `./generated/wire.gen.ts`. DO NOT hand-edit the generated file: it is
 * regenerated by the `export_bindings` tests in `muta-contracts`
 * (`cargo test -p muta-contracts --lib export_bindings -- --test-threads=1`).
 * CI regenerates it and fails on any diff, so commit the regenerated file
 * alongside any contract change.
 *
 * Hand-maintained below: the `Wire` union (ADR-0134 keeps it hand-written —
 * the Rust envelope references TUI-only response variants the panel never
 * consumes), `ControlReply` (a `Wire` variant, not a standalone contract
 * type), the `AgentResponse` union (same TUI-only reason), and the
 * client-side helpers. `AttachAction`, `ControlRequest`, `SessionOverview`,
 * `MonitorAction`, and every payload type are generated.
 *
 * JSON shapes follow serde's representations exactly:
 *
 * - `Wire` envelopes: `#[serde(tag = "type")]`. `Request` / `Response` /
 *   `Monitor` payloads are flattened, so an `AgentRequest`/`AgentResponse`
 *   variant appears as a key next to `"type"`, e.g.
 *   `{"type":"Request","Chat":{"text":"…","images":[]}}`. Flattened unit
 *   variants take `null` (`{"type":"Request","Interrupt":null}`) — see the
 *   `AgentRequest` alias below for how that maps onto the generated union.
 * - `AgentResponse::Round` nests its `RoundEvent` under `"event"`, where a
 *   nested unit variant serializes as a bare string (`"event": "StreamStart"`)
 *   and newtype variants as `{"StreamDelta": "…"}`.
 * - `MonitorEvent`: `#[serde(tag = "kind", rename_all = "snake_case")]`,
 *   flattened into the envelope — its fields sit at the top level of the
 *   Monitor frame alongside `type`/`kind`.
 * - Enums without `rename_all` (Role, PermissionDecision, ReviewStatus…)
 *   keep PascalCase variant names on the wire; enums with it (SessionStatus,
 *   MonitorEvent kinds, notices…) use snake_case. The generated file mirrors
 *   the serde attributes, so casing can no longer drift.
 *
 * Wire data is authored by the daemon, so extra fields are tolerated (and
 * relied on) for forward compatibility.
 */

export * from "./generated/wire.gen.js";
import type { WebConfigView } from "./generated/wire.gen.js";

import type {
  AgentRequest as AgentRequestPayload,
  AttachAction,
  CommandRecord,
  CommandCatalog,
  ComposerCompletion,
  ImagePart,
  Message,
  MonitorEvent,
  PermissionDecision,
  ProviderPickerSnapshot,
  QueuedMessage,
  RetryResolution,
  RoundEvent,
  RoundInterrupt,
  RoundSummary,
  SessionOverview,
} from "./generated/wire.gen.js";

export type QueuedUserInput = QueuedMessage;

// Agent requests (client → daemon), as flattened into `Wire::Request`.

/**
 * serde flattens the externally-tagged `AgentRequest` into the `Wire::Request`
 * envelope, where a flattened unit variant appears as `{ "Variant": null }`
 * (`{"type":"Request","Interrupt":null}`) instead of the bare string ts-rs
 * models for the standalone enum. This maps the generated union onto the
 * on-the-wire envelope shapes.
 */
type FlattenedIntoEnvelope<T> = T extends string ? { [Variant in T]: null } : T;

/** `AgentRequest` as it appears flattened inside `Wire::Request`. */
export type AgentRequest = FlattenedIntoEnvelope<AgentRequestPayload>;

// Monitor plane (flattened `Wire::Monitor` frames).

/**
 * `MonitorEvent` flattened into the envelope (tag `kind`, snake_case). The
 * variant payload fields sit directly on the Monitor frame: a snapshot frame
 * reads `{"type":"Monitor","kind":"snapshot","project_root":"…",…}` and a
 * session row arrives flattened as the row object itself on `session_added` /
 * `session_updated`.
 */
export type MonitorFrame = { type: "Monitor" } & MonitorEvent;

/** The `kind` tag values of a monitor frame. */
export type MonitorEventKind = MonitorEvent["kind"];

// Round-summary helpers (mirror `RoundSummary::{active_ms, tps}` in
// crates/muta-contracts/src/events.rs).

/** Mirrors `RoundSummary::active_ms` (wall-clock minus human-decision pause). */
export function roundActiveMs(s: RoundSummary): number {
  return Math.max(0, s.duration_ms - s.paused_ms);
}

/** Mirrors `RoundSummary::tps`; `0` when there is no usable denominator. */
export function roundTps(s: RoundSummary): number {
  const denominator = s.generation_ms > 0 ? s.generation_ms : roundActiveMs(s);
  return denominator === 0 ? 0 : (s.output_tokens * 1000) / denominator;
}

// Agent responses (daemon → client), flattened into `Wire::Response`.
// hand-maintained: `AgentResponse` carries many TUI-only variants (session
// context modal, token-usage report, OAuth connect status, /btw asides…)
// that the Web app never consumes; only the subset below is modeled.

export interface WelcomePayload {
  session_id: string;
  round_counter: number;
  messages: Message[];
  provider: string;
  model: string;
  /** Round-interrupt records (C11); absent on older daemons. */
  round_interrupts?: RoundInterrupt[];
  /** Retry-resolution records; absent on older daemons. */
  retry_resolutions?: RetryResolution[];
  /** Backend-owned command vocabulary shared with every frontend. */
  command_catalog?: CommandCatalog;
}

export interface ConversationReplacedPayload {
  session_id: string;
  messages: Message[];
  /** Command-ledger rows (ADR-0091); absent on older daemons. */
  commands?: CommandRecord[];
  /** Round-interrupt records (C11); absent on older daemons. */
  round_interrupts?: RoundInterrupt[];
  /** Retry-resolution records; absent on older daemons. */
  retry_resolutions?: RetryResolution[];
}

export type AgentResponse =
  | { Round: { session_id: string; event: RoundEvent } }
  | { ProviderKeys: [string, boolean][] }
  | { ProviderPicker: ProviderPickerSnapshot }
  | { ProviderSwitched: { provider: string; model: string } }
  | {
      ComposerCompletions: {
        request_id: number;
        text: string;
        cursor: number;
        items: ComposerCompletion[];
      };
    }
  // Unit variant: `{"ConversationCleared":null}` — it carries no id; the
  // fresh session's id arrives tagging the next `Round` event (handoff in
  // the store).
  | { ConversationCleared: null }
  | { ConversationReplaced: ConversationReplacedPayload }
  | { CopyToClipboard: { text: string } }
  | { WebSearchConfigSnapshot: WebConfigView }
  | { WebSearchConfigUpdated: WebConfigView }
  | { Error: string }
  | { Exit: null };

// Transport envelope (crates/muta-contracts/src/wire.rs since ADR-0134) —
// `AttachAction`, `ControlRequest`, and `SessionOverview` are GENERATED now
// (the generated file is the single mirror of the Rust serde truth) and
// re-exported through the barrel at the top of this file; only the `Wire`
// union itself and the web-only payload unions remain hand-written here
// (the Rust `Wire` references TUI-only response variants the panel never
// consumes, so generating the envelope wholesale would drag those in).

export interface ControlReply {
  ok: boolean;
  session_id?: string;
  error?: string;
}

export type Wire =
  | ({ type: "Select" } & {
      action: AttachAction;
      project?: string;
      version?: string;
      /** Wire protocol number (ADR-0134); the daemon's compatibility gate. */
      protocol?: number;
    })
  | ({ type: "Welcome" } & WelcomePayload)
  | ({ type: "Pick" } & { sessions: SessionOverview[] })
  | ({ type: "Error" } & {
      message: string;
      /** Stable machine-readable reason (ADR-0105), e.g. `"version_mismatch"`. */
      code?: string | null;
    })
  | ({ type: "Request" } & AgentRequest)
  | ({ type: "Response" } & AgentResponse)
  | ({ type: "ControlReply" } & ControlReply)
  | MonitorFrame;
