// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Consequence / threat level of a tool invocation.
 *
 * Distinguishes harmless read-only inspection from destructive mutations,
 * command executions, and process lifecycle operations.
 */
export type HazardLevel = "safe" | "file_modification" | "command_execution" | "process_lifecycle" | "network_or_external";
