// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of file change in a [`ToolOutput::Patch`].
 */
export type PatchOp = "Create" | "Edit" | "Delete";
