// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of extended thinking a model supports, and how it is encoded on the wire.
 */
export type ReasoningSupport = "none" | "reasoning_content" | "reasoning_summary" | "anthropic_adaptive" | "anthropic_adaptive_always_on" | "anthropic_adaptive_on_by_default" | "anthropic_manual";
