// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A string whose [`Debug`] and [`std::fmt::Display`] implementations redact
 * the contents.
 *
 * The underlying value is still reachable via [`Self::expose_secret`] — the
 * redaction only prevents accidental leaks through `{:?}` or `{}` formatting.
 * Serde is transparent: the value (de)serializes exactly like a plain
 * `String`, so on-disk shapes (`config.toml`, `credentials.toml`,
 * `auth.toml`) are unchanged and existing files need no migration.
 */
export type SecretString = string;
