// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The provenance of a session relative to its lineage.
 */
export type SessionForkKind = "trunk" | "fork" | "aside" | "subagent";
