// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The resume-time "working memory" projection of a session: a headline, the
 * user's intent, and a running checklist of what has happened.
 */
export type SessionDigest = { 
/**
 * Cleaned, concise title (3-7 words) — the picker row's headline.
 */
title: string, 
/**
 * One or two sentences stating what the user wants out of this session.
 */
intent: string, 
/**
 * Running checklist of what has been done and decided, oldest first.
 */
history: Array<string>, };
