// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a shell step stopped. Drives the themed termination footer (L6) so the
 * user and the model can tell *why* a command ended — not just that it did.
 * A healthy `Exited` run is silent; every other variant renders a coloured
 * marker. Back-compat: restored sessions without this field deserialize as
 * [`ShellTermination::Exited`].
 */
export type ShellTermination = "Exited" | "IdleBlocked" | "InteractiveBlocked" | "InputUnanswered" | "Detached" | "Timeout" | "Cancelled" | "StreamGuard";
