// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which pipe a captured shell line came from. Lets the renderer colour
 * stderr distinctly while still emitting lines in their true arrival order
 * (interleaved), instead of the all-stdout-then-all-stderr split that lost
 * timing for tools like `cargo`/`git`/`npm`.
 */
export type ShellStream = "Out" | "Err";
