// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoItem } from "./TodoItem";

/**
 * The whole task list. Display order is the [`Vec`] order; identity is
 * [`TodoItem::id`]. Invariants (unique ids, ≤ [`MAX_TODOS`] items, ≤ one
 * `InProgress`) are enforced by the constructors and mutators, never by
 * callers.
 */
export type TodoList = { items: Array<TodoItem>, 
/**
 * Next id to hand out. Monotonic for the life of the list so ids are
 * never reused after a removal, even across save/resume.
 */
next_id: bigint, 
/**
 * Harness round counter value the last time the list changed. The TUI
 * compares this against the current round counter to flag a stale panel.
 */
updated_at_round: bigint, };
