// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoId } from "./TodoId";
import type { TodoStatus } from "./TodoStatus";

export type TodoItem = { id: TodoId, content: string, status: TodoStatus, 
/**
 * Unix-epoch seconds when the item was first created. Preserved across
 * reconciliations (the model re-sending the same content does not reset
 * the clock).
 */
created_at: bigint, 
/**
 * Unix-epoch seconds of the last status change. Bumped only when the
 * status actually differs, not on every no-op reconcile.
 */
updated_at: bigint, };
