// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, monotonic identifier for a single todo item. Opaque to callers —
 * display and references use position/content, not this value. Serialized
 * transparently so persisted lists stay compact.
 */
export type TodoId = bigint;
