// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a single todo item.
 */
export type TodoStatus = "pending" | "in_progress" | "completed" | "cancelled";
