// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessKillSpec } from "./ProcessKillSpec";

/**
 * Detailed, tool-specific payload submitted to the permission handler.
 */
export type ToolPermissionPayload = { "kind": "file_edit", 
/**
 * Target file path(s) being created or modified.
 */
paths: Array<string>, 
/**
 * Specific operation (e.g. "write_to_file", "replace_file_content").
 */
operation: string, } | { "kind": "command", 
/**
 * The full command line to execute.
 */
command: string, 
/**
 * Working directory.
 */
cwd: string | null, 
/**
 * Process group / pkill descriptor for emergency or cancellation termination.
 */
kill_spec: ProcessKillSpec, } | { "kind": "process", target: string, action: string, } | { "kind": "generic", summary: string, details: unknown, };
