// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HazardLevel } from "./HazardLevel";
import type { ToolPermissionPayload } from "./ToolPermissionPayload";

/**
 * Complete submission from a tool to the permission handler.
 */
export type ToolPermissionSubmission = { 
/**
 * Threat / Hazard classification of the tool invocation.
 */
hazard_level: HazardLevel, 
/**
 * User-friendly label for the operation.
 */
label: string, 
/**
 * Detailed consequence description.
 */
description: string, 
/**
 * Canonical scope string for allowlist matching (e.g. path or command pattern).
 */
scope: string, 
/**
 * Structured tool-specific payload.
 */
payload: ToolPermissionPayload, };
