// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "../../web/src/lib/generated/wire.gen";
import type { PatchOp } from "./PatchOp";
import type { ShellLine } from "./ShellLine";
import type { ShellTermination } from "./ShellTermination";
import type { TokenUsage } from "./TokenUsage";
import type { WebSearchHit } from "./WebSearchHit";

/**
 * Typed result of a tool invocation.
 *
 * Neither `PartialEq` nor `Eq` is derived: the [`ToolOutput::Subagent`]
 * variant carries `Vec<Message>` and `Message` does not implement either
 * trait (its `Vec<ImagePart>` base64 payloads make structural equality
 * expensive and uninteresting). Compare via [`ToolOutput::to_text`] or by
 * pattern-matching on the variant in tests.
 */
export type ToolOutput = { "Text": string } | { "Error": { message: string, detail: string | null, } } | { "PermissionDenied": { tool: string, } } | { "Shell": { command: string, stdout: string, stderr: string, lines: Array<ShellLine>, exit: number | null, truncated: boolean, 
/**
 * Why the step ended. Back-compat: restored sessions without this
 * field deserialize as [`ShellTermination::Exited`] (via
 * `#[serde(default)]`), so a live step whose cause wasn't persisted
 * reads as a normal exit rather than failing to load.
 */
termination: ShellTermination, 
/**
 * Set only with [`ShellTermination::Detached`] (ADR-0190): the
 * background-job id the child was adopted under, so the UI can point
 * at the notification target.
 */
detached_job_id?: string | null, } } | { "Code": { lang: string | null, text: string, start_line: number, prefix: string | null, suffix: string | null, } } | { "Listing": { entries: Array<string>, } } | { "Matches": { pattern: string, lines: Array<string>, } } | { "Patch": { path: string, op: PatchOp, old: string, new: string, start_line: number, 
/**
 * Advisory diagnostics for a committed change; never a mutation failure.
 */
warnings?: Array<string>, } } | { "Subagent": { summary: string, messages: Array<Message>, usage: TokenUsage, 
/**
 * Time the subagent's own provider requests spent *generating*
 * (completion-spanning, excluding tool execution and human pauses),
 * so the parent round can fold it into its throughput denominator.
 * Without this, the subagent's output tokens would be in the parent's
 * numerator but its generation time missing from the denominator —
 * inflating the displayed tok/s for any delegating round.
 */
generation_ms: bigint, failed: boolean, interrupted: boolean, } } | { "Image": { mime: string, data: string, } } | { "WebSearch": { query: string, provider: string, results: Array<WebSearchHit>, truncated: boolean, } } | { "WebArticle": { url: string, title?: string | null, domain: string, markdown: string, reader: string, tokens: number, truncated: boolean, } };
