// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An incremental chunk streamed by a long-running tool before its final
 * output lands. Lets the UI render partial output (e.g. a bash command's
 * stdout as it arrives) instead of freezing on a spinner until the process
 * exits.
 */
export type ToolStream = { "Stdout": string } | { "Stderr": string };
