// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransportObservation = "unreported" | "pooled_connection" | "cold_connection";
