// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Concrete domains for project asset trust.
 *
 * `all` is deliberately not a domain. It is a command-layer selection that
 * expands to [`TrustDomain::ALL`]. Persisting an aggregate grant would create
 * a second source of truth and make a concrete domain impossible to revoke.
 */
export type TrustDomain = "mcp" | "skills" | "hooks" | "instructions" | "ex_workspace" | "user_assets";
