// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single search hit within [`ToolOutput::WebSearch`].
 */
export type WebSearchHit = { title: string, url: string, domain: string, snippet: string, };
