// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trust state for one project-authored asset domain.
 */
export type WorkspaceTrustState = "absent" | "quarantined" | "trusted" | "denied" | "changed" | "expired";
