// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceTrustState } from "./WorkspaceTrustState";

/**
 * First-class security state attached to every harness snapshot.
 */
export type WorkspaceSecuritySnapshot = { 
/**
 * Canonical exact workspace root used for persisted decisions.
 */
root: string, 
/**
 * Trust status for MCP domain.
 */
mcp: WorkspaceTrustState, 
/**
 * Trust status for Skills domain.
 */
skills: WorkspaceTrustState, 
/**
 * Trust status for lifecycle hooks.
 */
hooks: WorkspaceTrustState, 
/**
 * Trust status for project instructions (AGENTS.md).
 */
instructions: WorkspaceTrustState, 
/**
 * Trust status for project-declared external workspace roots.
 */
ex_workspace: WorkspaceTrustState, 
/**
 * Trust status for user-level MCP and global executable assets (ADR-0252).
 */
user_assets: WorkspaceTrustState, };
