// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningSupport } from "./ReasoningSupport";
import type { WireProtocol } from "./WireProtocol";

/**
 * A user's explicit capability override for one (provider-instance, model)
 * route -- the **top layer** of the capability resolution order (ADR-0149).
 *
 * Every field is optional; `None` means "no opinion, fall through to the
 * layer below". A present `Some(false)` is meaningful: it forces the
 * capability off even when both the remote advertisement and the static
 * baseline say otherwise (e.g. a relay's `glm-5.3-flash` that strips image
 * inputs, or an account whose plan caps the context window lower than the
 * model card claims).
 *
 * This lives in `muta-contracts` (not persistence) so the merge function can
 * live beside the structure it overrides -- persistence keys it per
 * `(instance_id, model_id)` inside `RouteSettings` and owns only storage.
 */
export type CapabilityOverrides = { 
/**
 * Explicit model route protocol; resolved independently from capabilities.
 */
protocol: WireProtocol | null, 
/**
 * Force the family tag used for family-scoped wire behavior (cache
 * policy, effort mapping). `None` -> inherit from the layers below.
 */
family: string | null, 
/**
 * Force the context window (tokens). `None` -> inherit.
 */
context_window: number | null, 
/**
 * Force the max output tokens. `None` -> inherit. `Some(0)` clears an
 * inherited cap.
 */
max_output_tokens: number | null, 
/**
 * Force the thinking representation. `None` -> inherit.
 */
thinking: ReasoningSupport | null, 
/**
 * Force native tool calling on/off. `None` -> inherit.
 */
tool_call: boolean | null, 
/**
 * Force image-input support on/off. `None` -> inherit.
 */
vision: boolean | null, };
