// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single recorded user input, tagged with the session and workspace it
 * came from plus the wall-clock time it was sent.
 *
 * The on-disk format is `Vec<HistoryEntry>`. `session_id` and `workspace`
 * are `Option` so that:
 * - entries recorded before origin-tracking existed (or by a process that
 *   could not learn its session id) load back as "unknown origin" rather
 *   than failing to parse, and
 * - the cross-process union merge can keep first-seen entries verbatim
 *   without having to fabricate an origin.
 */
export type HistoryEntry = { 
/**
 * The user's literal prompt text, sent verbatim to the agent.
 */
text: string, 
/**
 * The id of the session this entry was typed into, or `None` when the
 * recording process could not attribute it (e.g. a legacy entry). The
 * inline ↑/↓ recall filters the global history by this field against
 * the live session id.
 */
session_id?: string | null, 
/**
 * The workspace (project root) the session was running in when this
 * entry was sent, or `None` when unknown. Surfaced in the history
 * surface's selected-row origin line so the user can tell a prompt
 * typed in another project apart from one typed here.
 */
workspace?: string | null, 
/**
 * When the entry was sent, as milliseconds since the UNIX epoch. Drives
 * the newest-first ordering of the history surface (most recent on top)
 * and the selected-row time stamp. Entries without a known time load as
 * `0` and sort oldest.
 */
created_at_ms: number, };
