// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of extended thinking a model supports, and **how it is encoded on
 * the wire**. [`ReasoningMode`] is the user's on/off *intent*; `ReasoningSupport`
 * is the model's *capability*, and the two combine at request-build time to
 * decide which (if any) `thinking` object the Anthropic transport emits.
 *
 * This is the single source of truth for thinking capability — the boolean
 * "does it reason" used for display derives from it via [`Self::reasons`].
 * Carried per-model in the registry exactly like [`crate::effort::Effort`]
 * levels, so the transport never guesses the wire form from a model id.
 *
 * The Anthropic Messages API exposes **two mutually exclusive** thinking
 * mechanisms, which is why a single bool is insufficient:
 * - **Adaptive** (`thinking: {type:"adaptive"}` + `output_config.effort`):
 *   the model decides depth per request. Opus 4.7+ accept *only* this; the
 *   legacy manual form is rejected with 400.
 * - **Manual** (`thinking: {type:"enabled", budget_tokens: N}`): a fixed token
 *   budget, no `effort`. The only form Haiku 4.5 / Opus·Sonnet 4.5 / Claude 4
 *   accept; needs the `interleaved-thinking` beta header alongside tools.
 */
export type ReasoningSupport = "none" | "reasoning_content" | "reasoning_summary" | "anthropic_adaptive" | "anthropic_adaptive_always_on" | "anthropic_adaptive_on_by_default" | "anthropic_manual";
