[package]
name = "nuo-providers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nuo-model-codec = { workspace = true }
nuo-contracts = { workspace = true }
bytes = { workspace = true }
http = "1.4"
httpdate = { workspace = true }
netune = "0.1.0"
netune-trace = "0.1.0"
nuo-persistence = { workspace = true }
nuo-host = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
toml = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
uuid = { workspace = true }
inventory = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync", "time"] }
tracing = { workspace = true }
chrono = { workspace = true }
fastrand = { workspace = true }
md-5 = { workspace = true }
rsa = { workspace = true }
cbc = { workspace = true }
aes = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[lints]
workspace = true
